create table if not exists public.waiting_list (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.waiting_list enable row level security;

create policy "Allow public waitlist signups"
  on public.waiting_list
  for insert
  to anon, authenticated
  with check (true);
